/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'liblzma_la-crc64-fast.o'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct elf64_hdr;
struct struct_elf_info;
struct elf64_phdr;
struct $8E3F17DF06268256B33C950219C36638;
struct struc_gots;
struct struc_parse_elf;

/* 1 */
struct __va_list_tag
{
  unsigned int gp_offset;
  unsigned int fp_offset;
  void *overflow_arg_area;
  void *reg_save_area;
};

/* 2 */
typedef __va_list_tag gcc_va_list[1];

/* 3 */
union __attribute__((aligned(8))) __m64
{
  unsigned __int64 m64_u64;
  float m64_f32[2];
  __int8 m64_i8[8];
  __int16 m64_i16[4];
  __int32 m64_i32[2];
  __int64 m64_i64;
  unsigned __int8 m64_u8[8];
  unsigned __int16 m64_u16[4];
  unsigned __int32 m64_u32[2];
};

/* 4 */
union __attribute__((aligned(16))) __m128
{
  float m128_f32[4];
  unsigned __int64 m128_u64[2];
  __int8 m128_i8[16];
  __int16 m128_i16[8];
  __int32 m128_i32[4];
  __int64 m128_i64[2];
  unsigned __int8 m128_u8[16];
  unsigned __int16 m128_u16[8];
  unsigned __int32 m128_u32[4];
};

/* 5 */
struct __m128d
{
  double m128d_f64[2];
};

/* 6 */
union __attribute__((aligned(16))) __m128i
{
  __int8 m128i_i8[16];
  __int16 m128i_i16[8];
  __int32 m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned __int32 m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

/* 7 */
union __attribute__((aligned(32))) __m256
{
  float m256_f32[8];
};

/* 8 */
union __attribute__((aligned(32))) __m256d
{
  double m256d_f64[4];
};

/* 9 */
union __attribute__((aligned(32))) __m256i
{
  __int8 m256i_i8[32];
  __int16 m256i_i16[16];
  __int32 m256i_i32[8];
  __int64 m256i_i64[4];
  unsigned __int8 m256i_u8[32];
  unsigned __int16 m256i_u16[16];
  unsigned __int32 m256i_u32[8];
  unsigned __int64 m256i_u64[4];
};

/* 10 */
union __attribute__((aligned(64))) __m512
{
  float m512_f32[16];
};

/* 11 */
union __attribute__((aligned(64))) __m512d
{
  double m512d_f64[8];
};

/* 12 */
union __attribute__((aligned(64))) __m512i
{
  __int8 m512i_i8[64];
  __int16 m512i_i16[32];
  __int32 m512i_i32[16];
  __int64 m512i_i64[8];
  unsigned __int8 m512i_u8[64];
  unsigned __int16 m512i_u16[32];
  unsigned __int32 m512i_u32[16];
  unsigned __int64 m512i_u64[8];
};

/* 14 */
struct lzma_allocator
{
  void (__fastcall *alloc)(struct_elf_info *opaque, size_t nmemb, size_t size);
  void (__fastcall *free)(struct_elf_info *opaque, void *ptr);
  void *elf_info;
};

/* 15 */
typedef struct elf64_hdr Elf64_Ehdr;

/* 28 */
struct struct_elf_info
{
  Elf64_Ehdr *elf_hdr;
  __int64 last_va;
  elf64_phdr *phdr_base;
  __int16 phnum;
  __attribute__((packed)) __attribute__((aligned(1))) int field_1A;
  __int64 vaddr;
  int dyn_length;
  int field_2C;
  __int64 dt_strtab;
  __int64 dt_symtab;
  void *JMPREL_addr;
  int plt_num;
  int relo_found;
  __int64 relo_vaddr;
  __int64 relo_size;
  __int64 dt_verdef;
  __int64 dt_verdefnum;
  __int64 dt_audit;
  __int64 dt_rela;
  int rela_num;
  int field_84;
  __int64 preinit_hash;
  int preinit_num;
  int field_94;
  __int64 field_98;
  __int64 field_A0;
  __int64 field_A8;
  __int64 field_B0;
  __int64 rw_hdr_file_end;
  __int64 total_free_wbss;
  __int64 total_free;
  char dt_flags;
  __attribute__((aligned(8))) int gnu_hash_nbuckets;
  int gnu_hash_bitmask_nwords_m1;
  int gnu_hash_shift;
  int field_E4;
  __int64 gnu_hash_indexbits;
  __int64 gnu_hash_arr;
  __int64 gnu_hash_chains;
};

/* 18 */
typedef unsigned __int16 uint16_t;

/* 17 */
typedef uint16_t Elf64_Half;

/* 20 */
typedef unsigned int uint32_t;

/* 19 */
typedef uint32_t Elf64_Word;

/* 22 */
typedef unsigned __int64 uint64_t;

/* 21 */
typedef uint64_t Elf64_Addr;

/* 23 */
typedef uint64_t Elf64_Off;

/* 16 */
struct elf64_hdr
{
  unsigned __int8 e_ident[16];
  Elf64_Half e_type;
  Elf64_Half e_machine;
  Elf64_Word e_version;
  Elf64_Addr e_entry;
  Elf64_Off e_phoff;
  Elf64_Off e_shoff;
  Elf64_Word e_flags;
  Elf64_Half e_ehsize;
  Elf64_Half e_phentsize;
  Elf64_Half e_phnum;
  Elf64_Half e_shentsize;
  Elf64_Half e_shnum;
  Elf64_Half e_shstrndx;
};

/* 33 */
typedef uint64_t Elf64_Xword;

/* 32 */
struct elf64_phdr
{
  Elf64_Word __p_type;
  Elf64_Word p_flags;
  Elf64_Off p_offset;
  Elf64_Addr p_vaddr;
  Elf64_Addr p_paddr;
  Elf64_Xword p_filesz;
  Elf64_Xword p_memsz;
  Elf64_Xword p_align;
};

/* 24 */
struct struct_ctx
{
  int num_imports;
  __attribute__((aligned(8))) int field_8;
  int field_C;
  __int64 field_10;
  __int64 exit;
  __int64 setresgid;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 fn_read;
  __int64 fn_errno_location;
  __int64 setlogmask;
  __int64 field_60;
  __int64 field_68;
  __int64 field_70;
  __int64 field_78;
  __int64 field_80;
  __int64 field_88;
  int field_90;
  int field_94;
  __int64 field_98;
  __int64 field_A0;
  __int64 field_A8;
  __int64 field_B0;
  __int64 field_B8;
  __int64 field_C0;
  __int64 field_C8;
  __int64 field_D0;
  __int64 field_D8;
  __int64 field_E0;
  __int64 field_E8;
  __int64 field_F0;
  __int64 field_F8;
  __int64 field_100;
  __int64 field_108;
  __int64 field_110;
  __int64 field_118;
  __int64 field_120;
  __int64 field_128;
  __int64 field_130;
  __int64 field_138;
  __int64 field_140;
  __int64 field_148;
  __int64 field_150;
};

/* 25 */
enum HASHES
{
  sshd_proc = 0x108,
  __libc_start_main = 0x228,
  __libc_stack_end = 0x2B0,
  x7fELF = 0x300,
  read = 0x308,
  BN_num_bits = 0x4E0,
  _r_debug = 0x5B0,
  _rtld_global = 0x5B8,
  BN_bn2bin = 0x6D0,
  __errno_location = 0x878,
  _exit = 0x8A8,
  GLIBC_2_2_5 = 0x8C0,
  _dl_audit_preinit = 0xA60,
  BN_bin2bn = 0xC40,
};

/* 27 */
struct rootkit_ctx
{
  __int64 runtime_addr;
  __int64 runtime_offset;
  __int64 cpuid_got_ptr;
  __int64 cpu_id_got;
  rootkit_ctx *self;
  __int64 got_ptr;
  __int64 field_30;
  __int64 field_38;
};

/* 31 */
struct parse_lib
{
  struc_parse_elf *parser;
  struct_elf_info **infos;
  __int64 *RSA_public_decrypt;
  __int64 *EVP_PKEY_set1_RSA;
  __int64 *RSA_get0_key;
  __int64 global_counter;
  __int64 field_30;
};

/* 29 */
struct elf_parse_result
{
  struct_elf_info **elf_info_arr;
  Elf64_Ehdr *elf_ehdr;
  char **argv0;
  __int64 cpuid_got_ptr;
  parse_lib libs;
  __int64 field_58;
};

/* 51 */
struct struc_parse_elf
{
  Elf64_Ehdr **ehdr;
  __int64 field_1;
  __int64 field_2;
  __int64 field3;
  __int64 field_4;
  __int64 field_5;
  struct_elf_info *elf_info_arr[5];
  struc_parse_elf *self_addr;
  struct_elf_info **elf_arrptr;
  struct_elf_info elf_infos[5];
};

/* 30 */
struct struc_2880
{
  __int64 field_0;
  __int64 field_8;
  __int64 field_10;
  __int64 backdoor_init_stage2;
  __int64 field_20;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  __int64 field_50;
  __int64 field_58;
  __int64 field_60;
  __int64 field_68;
  __int64 field_70;
  __int64 field_78;
  __int64 field_80;
  __int64 field_88;
  __int64 field_90;
  __int64 field_98;
  __int64 field_A0;
  __int64 field_A8;
  __int64 field_B0;
  __int64 field_B8;
  __int64 field_C0;
  __int64 field_C8;
  __int64 field_D0;
  __int64 field_D8;
  __int64 field_E0;
  __int64 field_E8;
  __int64 field_F0;
  __int64 field_F8;
  __int64 field_100;
  __int64 field_108;
  __int64 field_110;
  __int64 field_118;
  int field_120;
  int field_124;
};

/* 34 */
struct struc_all
{
  __int64 field_0;
  __int64 field_8;
  __int64 field_10;
  __int64 field_18;
  __int64 field_20;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
};

/* 35 */
enum MACRO_PT
{
  PT_NULL = 0,
  PT_LOAD = 1,
  PT_DYNAMIC = 2,
  PT_INTERP = 3,
  PT_NOTE = 4,
  PT_SHLIB = 5,
  PT_PHDR = 6,
  PT_TLS = 7,
  PT_NUM = 8,
  PT_LOOS = 1610612736,
  PT_GNU_EH_FRAME = 1685382480,
  PT_GNU_STACK = 1685382481,
  PT_GNU_RELRO = 1685382482,
  PT_LOSUNW = 1879048186,
  PT_SUNWBSS = 1879048186,
  PT_SUNWSTACK = 1879048187,
  PT_HISUNW = 1879048191,
  PT_HIOS = 1879048191,
  PT_LOPROC = 1879048192,
  PT_HIPROC = 2147483647,
};

/* 36 */
typedef struct $8E3F17DF06268256B33C950219C36638 Elf64_Dyn;

/* 39 */
typedef __int64 int64_t;

/* 38 */
typedef int64_t Elf64_Sxword;

/* 40 */
union $8E3F17DF06268256B33C950219C36638::$933121F4FA1889599F702E16603DBB9F
{
  Elf64_Xword d_val;
  Elf64_Addr d_ptr;
};

/* 37 */
struct $8E3F17DF06268256B33C950219C36638
{
  Elf64_Sxword d_tag;
  union $8E3F17DF06268256B33C950219C36638::$933121F4FA1889599F702E16603DBB9F d_un;
};

/* 41 */
enum MACRO_DT
{
  DT_NULL = 0,
  DT_NEEDED = 1,
  DT_PLTRELSZ = 2,
  DT_PLTGOT = 3,
  DT_HASH = 4,
  DT_STRTAB = 5,
  DT_SYMTAB = 6,
  DT_RELA = 7,
  DT_RELASZ = 8,
  DT_RELAENT = 9,
  DT_STRSZ = 10,
  DT_SYMENT = 11,
  DT_INIT = 12,
  DT_FINI = 13,
  DT_SONAME = 14,
  DT_RPATH = 15,
  DT_SYMBOLIC = 16,
  DT_REL = 17,
  DT_RELSZ = 18,
  DT_RELENT = 19,
  DT_PLTREL = 20,
  DT_DEBUG = 21,
  DT_TEXTREL = 22,
  DT_JMPREL = 23,
  DT_BIND_NOW = 24,
  DT_INIT_ARRAY = 25,
  DT_FINI_ARRAY = 26,
  DT_INIT_ARRAYSZ = 27,
  DT_FINI_ARRAYSZ = 28,
  DT_RUNPATH = 29,
  DT_FLAGS = 30,
  DT_ENCODING = 32,
  DT_PREINIT_ARRAY = 32,
  DT_PREINIT_ARRAYSZ = 33,
  DT_NUM = 34,
  DT_LOOS = 1610612749,
  DT_HIOS = 1879044096,
  DT_LOPROC = 1879048192,
  DT_HIPROC = 2147483647,
  DT_VALRNGLO = 1879047424,
  DT_GNU_PRELINKED = 1879047669,
  DT_GNU_CONFLICTSZ = 1879047670,
  DT_GNU_LIBLISTSZ = 1879047671,
  DT_CHECKSUM = 1879047672,
  DT_PLTPADSZ = 1879047673,
  DT_MOVEENT = 1879047674,
  DT_MOVESZ = 1879047675,
  DT_FEATURE_1 = 1879047676,
  DT_POSFLAG_1 = 1879047677,
  DT_SYMINSZ = 1879047678,
  DT_SYMINENT = 1879047679,
  DT_VALRNGHI = 1879047679,
  DT_VALNUM = 12,
  DT_ADDRRNGLO = 1879047680,
  DT_GNU_HASH = 1879047925,
  DT_TLSDESC_PLT = 1879047926,
  DT_TLSDESC_GOT = 1879047927,
  DT_GNU_CONFLICT = 1879047928,
  DT_GNU_LIBLIST = 1879047929,
  DT_CONFIG = 1879047930,
  DT_DEPAUDIT = 1879047931,
  DT_AUDIT = 1879047932,
  DT_PLTPAD = 1879047933,
  DT_MOVETAB = 1879047934,
  DT_SYMINFO = 1879047935,
  DT_ADDRRNGHI = 1879047935,
  DT_ADDRNUM = 11,
  DT_VERSYM = 1879048176,
  DT_RELACOUNT = 1879048185,
  DT_RELCOUNT = 1879048186,
  DT_FLAGS_1 = 1879048187,
  DT_VERDEF = 1879048188,
  DT_VERDEFNUM = 1879048189,
  DT_VERNEED = 1879048190,
  DT_VERNEEDNUM = 1879048191,
  DT_VERSIONTAGNUM = 16,
  DT_AUXILIARY = 2147483645,
  DT_FILTER = 2147483647,
  DT_EXTRANUM = 3,
};

/* 42 */
enum dt_flags
{
  PLT = 0x1,
  PRE_INIT = 0x4,
  VERDEF = 0x8,
  AUDIT = 0x10,
  DF_NOW = 0x20,
};

/* 44 */
typedef unsigned int __u32;

/* 43 */
struct hashlimit_cfg
{
  __u32 mode;
  __u32 avg;
  __u32 burst;
  __u32 size;
  __u32 max;
  __u32 gc_interval;
  __u32 expire;
};

/* 45 */
struct gnu_hash
{
  int nbuckets;
  int symbolbase;
  int bitmask_nwords;
  int gnu_shift;
  __int64 indexbits_len;
  __int64 field_18;
  __int64 field_20;
};

/* 46 */
struct struc_vtbl
{
  __int64 field_0;
  __int64 field_8;
  __int64 field_10;
  __int64 field_18;
  __int64 field_20;
  __int64 field_28;
  struc_gots *static_gots;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  __int64 field_50;
  __int64 field_58;
  __int64 field_60;
  __int64 field_68;
  __int64 field_70;
  __int64 field_78;
  __int64 field_80;
};

/* 49 */
struct struc_gots
{
  __int64 field_0;
  __int64 cpu_id;
  __int64 backdoor_init_stage2;
};

/* 47 */
struct struc_init22
{
  __int64 field_0;
  struc_gots *static_gots;
  __int64 cpuid_got_ptr;
  __int64 field_18;
  __int64 field_20;
  __int64 field_28;
  __int64 field_30;
  __int64 field_38;
  __int64 field_40;
  __int64 field_48;
  __int64 field_50;
  __int64 field_58;
  __int64 field_60;
  __int64 field_68;
  __int64 field_70;
  __int64 field_78;
  rootkit_ctx *rookit_ctx;
};

/* 48 */
struct struc_13
{
  __int64 field_0;
  struct_elf_info *elf_info;
  __int64 field_10;
};

/* 50 */
struct struc_Lencoder
{
  __int64 field_0;
  __int64 backdoor_vtbl_init;
  __int64 field_10;
  __int64 field_18;
  __int64 import_lookup_ex;
  __int64 field_28;
  __int64 parse_elf;
};

